# Generated by Django 3.2.7 on 2021-09-12 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import utils.utils_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('personal_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='شماره شناسنامه')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('date', models.DateField(default=django.utils.datetime_safe.datetime.utcnow)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(default=utils.utils_functions.generate_random_string, max_length=8, verbose_name='کد تخفیف')),
                ('end_date', models.DateTimeField(default=utils.utils_functions.validate_discount_date, help_text='تاریخ به طور خودکار تا یک ماه دیگر تنظیم شده است', verbose_name='تاریخ انقضا')),
                ('customer', models.ForeignKey(help_text='روی علامت جستجو کلیک کرده و مشتری را بر اساس شماره تلفن پیدا کنید', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری')),
            ],
        ),
    ]
