# Generated by Django 3.2.7 on 2021-10-07 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.utils_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('personal_id', models.CharField(blank=True, max_length=200, null=True, validators=[utils.utils_functions.check_personal_code_is_valid], verbose_name='شماره شناسنامه')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('nl', 'Persian')], default='fa-ir', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(default=utils.utils_functions.generate_random_string, max_length=8, verbose_name='کد تخفیف')),
                ('end_date', models.DateTimeField(default=utils.utils_functions.validate_discount_date, help_text='تاریخ به طور خودکار تا یک ماه دیگر تنظیم شده است', verbose_name='تاریخ انقضا')),
                ('customer', models.ForeignKey(help_text='روی علامت جستجو کلیک کرده و مشتری را بر اساس شماره تلفن پیدا کنید', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(0, 'آذربايجان شرقي'), (1, 'آذربايجان غربي'), (2, 'اردبيل'), (3, 'اصفهان'), (4, 'ايلام'), (5, 'بوشهر'), (6, 'تهران'), (7, 'چهارمحال وبختياری'), (8, 'خراسان جنوبي'), (9, 'خراسان رضوئ'), (10, 'خراسان شمالي'), (11, 'خوزستان'), (12, 'زنجان'), (13, 'سمنان'), (14, 'سيستان وبلوچستان'), (15, 'فارس'), (16, 'قزوين'), (17, 'قم'), (18, 'البرز'), (19, 'كردستان'), (20, 'كرمان'), (21, 'كرمانشاه'), (22, 'كهكيلويه و بويراحمد'), (23, 'گلستان'), (24, 'گيلان'), (25, 'لرستان'), (26, 'مازندران'), (27, 'مركزي'), (28, 'هرمزگان'), (29, 'همدان'), (30, 'یزد')], max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('street', models.CharField(max_length=200, verbose_name='خیابان')),
                ('avenue', models.CharField(blank=True, max_length=200, null=True, verbose_name='کوچه')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('building_number', models.CharField(max_length=10, verbose_name='پلاک خانه')),
                ('building_unit', models.PositiveIntegerField(verbose_name='واحد')),
                ('receiver_first_name', models.CharField(max_length=250)),
                ('receiver_last_name', models.CharField(max_length=250)),
                ('receiver_phone', models.CharField(max_length=11)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری')),
            ],
        ),
    ]
