# Generated by Django 3.2.7 on 2021-10-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='receiver_first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='receiver_last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='receiver_phone',
        ),
    ]
