# Generated by Django 3.2.7 on 2021-10-08 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211007_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='avenue',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_address',
            field=models.TextField(default=None, verbose_name='آدرس پستی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_first_name',
            field=models.CharField(default=None, max_length=250, verbose_name='نام گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_last_name',
            field=models.CharField(default=None, max_length=250, verbose_name='نام خانوادگی گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_phone',
            field=models.CharField(default=None, max_length=11, validators=[django.core.validators.RegexValidator(message='کدپستی باید ۱۰ رقم و بدون خط تیره باشد', regex='^09\\d{9}')], verbose_name='شماره گیرنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.PositiveIntegerField(verbose_name='پلاک خانه'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_unit',
            field=models.CharField(max_length=5, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='کدپستی باید ۱۰ رقم و بدون خط تیره باشد', regex='\\d{10}')], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
    ]
