# Generated by Django 3.2.7 on 2021-09-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='choice',
        ),
        migrations.AddField(
            model_name='address',
            name='avenue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='کوچه'),
        ),
        migrations.AddField(
            model_name='address',
            name='building_number',
            field=models.CharField(default=None, max_length=10, verbose_name='پلاک خانه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='building_unit',
            field=models.PositiveIntegerField(default=None, verbose_name='واحد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=100, verbose_name='شهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=None, max_length=12, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=None, max_length=10, verbose_name='کد پستی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('آذربايجان شرقي', 0), ('آذربايجان غربي', 1), ('اردبيل', 2), ('اصفهان', 3), ('ايلام', 4), ('بوشهر', 5), ('تهران', 6), ('چهارمحال بختياري', 7), ('خراسان جنوبي', 8), ('خراسان رضوي', 9), ('خراسان شمالي', 10), ('خوزستان', 11), ('زنجان', 12), ('سمنان', 13), ('سيستان و بلوچستان', 14), ('فارس', 15), ('قزوين', 16), ('قم', 17), ('البرز', 18), ('كردستان', 19), ('كرمان', 20), ('كرمانشاه', 21), ('كهكيلويه و بويراحمد', 22), ('گلستان', 23), ('گيلان', 24), ('لرستان', 25), ('مازندران', 26), ('مركزي', 27), ('هرمزگان', 28), ('همدان', 29), ('يزد', 30)], default=None, max_length=100, verbose_name='استان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=None, max_length=200, verbose_name='خیابان'),
            preserve_default=False,
        ),
    ]
