# Generated by Django 3.2.7 on 2021-09-18 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام'),
        ),
    ]
