# Generated by Django 3.2.7 on 2021-09-08 22:03

from django.db import migrations, models
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='end_date',
            field=models.DateTimeField(default=utils.utils_functions.validate_discount_date),
        ),
    ]
