# Generated by Django 3.2.7 on 2021-09-18 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='personal_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
    ]
