# Generated by Django 3.2.7 on 2021-10-08 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211008_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receiver_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن خود را بدون صفر وارد کنید. مانند : ۹۱۲۱۲۳۴۵۶۷', regex='^09\\d{9}')], verbose_name='شماره گیرنده'),
        ),
    ]
