# Generated by Django 3.2.7 on 2021-09-08 22:14

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_discountcode_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='customer',
            field=models.ForeignKey(help_text='روی علامت جستجو کلیک کرده و مشتری را بر اساس شماره تلفن پیدا کنید', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_code',
            field=models.CharField(default=utils.utils_functions.generate_random_string, max_length=8, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='end_date',
            field=models.DateTimeField(default=utils.utils_functions.validate_discount_date, help_text='تاریخ به طور خودکار تا یک ماه دیگر تنظیم شده است', verbose_name='تاریخ انقضا'),
        ),
    ]
