# Generated by Django 3.2.7 on 2021-09-20 17:12

from django.db import migrations, models
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210918_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='personal_id',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[utils.utils_functions.check_personal_code_is_valid], verbose_name='شماره شناسنامه'),
        ),
    ]
