# Generated by Django 3.2.7 on 2021-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl', 'Persian')], default='fa-ir', max_length=5),
        ),
    ]
