# Generated by Django 3.2.7 on 2021-10-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_discountcode_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='customer',
            field=models.OneToOneField(help_text='روی علامت جستجو کلیک کرده و مشتری را بر اساس شماره تلفن پیدا کنید', on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری'),
        ),
    ]
