# Generated by Django 3.2.7 on 2021-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_discountcode_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_amount',
            field=models.FloatField(default=0, verbose_name='تخفیف'),
        ),
    ]
