# Generated by Django 3.2.7 on 2021-09-25 23:23

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='نام')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='والد')),
            ],
            options={
                'ordering': ('parent__name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('price', models.FloatField(default=0, verbose_name='قیمت')),
                ('quantity', models.IntegerField(default=0, help_text='در صورت صفر بودن تعداد محصول از طریق تعداد در ویژگی های کلیدی محاسبه میشود', verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='نام')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productproperty', verbose_name='ویژگی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.utils_functions.image_path_generator)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFactorProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='مقدار')),
                ('price_impact', models.FloatField(default=0, verbose_name='تاثیر بر قیمت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productproperty', verbose_name='ویژگی کلیدی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('discount_amount', models.FloatField()),
                ('percent_mode', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
