# Generated by Django 3.2.7 on 2021-10-16 13:43

from django.db import migrations, models
import django.db.models.deletion
import utils.utils_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='نام')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='والد')),
            ],
            options={
                'ordering': ('parent__name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('price', models.FloatField(default=0, verbose_name='قیمت')),
                ('quantity', models.IntegerField(default=0, help_text='در صورت صفر بودن تعداد محصول از طریق تعداد در ویژگی های کلیدی محاسبه میشود', verbose_name='موجودی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='نام')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='دسته')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('show_in_top_properties', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productproperty', verbose_name='ویژگی')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.utils_functions.image_path_generator)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFactorProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='مقادیر ویژگی های کلیدی')),
                ('price_impact', models.FloatField(default=0, verbose_name='تاثیر بر قیمت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('discount_amount', models.FloatField()),
                ('percent_mode', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#00ffff', 'aqua'), ('#000000', 'black'), ('#0000ff', 'blue'), ('#ff00ff', 'fuchsia'), ('#008000', 'green'), ('#808080', 'gray'), ('#00ff00', 'lime'), ('#800000', 'maroon'), ('#000080', 'navy'), ('#808000', 'olive'), ('#800080', 'purple'), ('#ff0000', 'red'), ('#c0c0c0', 'silver'), ('#008080', 'teal'), ('#ffffff', 'white'), ('#ffff00', 'yellow')], max_length=100)),
                ('price_impact', models.FloatField(default=0, verbose_name='تاثیر بر قیمت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='رنگ')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='factor_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productproperty', verbose_name='ویژگی کلیدی'),
        ),
    ]
