# Generated by Django 3.2.7 on 2021-09-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfactorproperty',
            name='property',
        ),
        migrations.AddField(
            model_name='product',
            name='factor_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productproperty', verbose_name='ویژگی کلیدی'),
        ),
    ]
