# Generated by Django 3.2.7 on 2021-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210926_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydescription',
            name='show_in_top_properties',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productfactorproperty',
            name='value',
            field=models.CharField(max_length=500, verbose_name='مقادیر ویژگی های کلیدی'),
        ),
    ]
