# Generated by Django 3.2.7 on 2021-09-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productproperty_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydescription',
            name='property',
            field=models.ForeignKey(limit_choices_to={'linename': 'foo'}, on_delete=django.db.models.deletion.RESTRICT, to='product.productproperty', verbose_name='ویژگی'),
        ),
    ]
