# Generated by Django 3.2.7 on 2021-09-13 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_propertydescription_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__name',)},
        ),
        migrations.AlterField(
            model_name='propertydescription',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productproperty', verbose_name='ویژگی'),
        ),
    ]
