# Generated by Django 3.2.7 on 2021-10-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfactorproperty',
            name='link_to_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor', verbose_name='رنگ'),
        ),
    ]
