# Generated by Django 3.2.7 on 2021-10-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productfactorproperty_link_to_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfactorproperty',
            name='link_to_color',
        ),
    ]
