# Generated by Django 3.2.7 on 2021-09-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthcode',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
