# Generated by Django 3.2.7 on 2021-09-15 14:56

from django.db import migrations, models
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userauthcode_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcode',
            name='code',
            field=models.CharField(default=utils.utils_functions.generate_random_code, max_length=5, verbose_name='کد تاییدیه'),
        ),
        migrations.AlterField(
            model_name='userauthcode',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='زمان انقضا'),
        ),
    ]
