# Generated by Django 3.2.7 on 2021-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210915_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcode',
            name='time',
            field=models.TimeField(verbose_name='زمان انقضا'),
        ),
    ]
