# Generated by Django 3.2.7 on 2021-09-15 15:04

from django.db import migrations, models
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userauthcode_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcode',
            name='time',
            field=models.TimeField(default=utils.utils_functions.compute_code_expire_time, verbose_name='زمان انقضا'),
        ),
    ]
