# Generated by Django 3.2.7 on 2021-09-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_costumer',
            new_name='is_customer',
        ),
    ]
