# Generated by Django 3.2.7 on 2021-09-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userauthcode_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthcode',
            old_name='time',
            new_name='exp_time',
        ),
    ]
