# Generated by Django 3.2.7 on 2021-09-15 16:07

from django.db import migrations, models
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_time_userauthcode_exp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcode',
            name='exp_time',
            field=models.DateTimeField(default=utils.utils_functions.compute_code_expire_time, verbose_name='زمان انقضا'),
        ),
    ]
