# Generated by Django 3.2.7 on 2021-09-14 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.utils_functions


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_is_costumer_user_is_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.utils_functions.generate_random_code, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
