# Generated by Django 3.2.7 on 2021-09-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210918_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
