# Generated by Django 3.2.7 on 2021-10-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('WAITING_FOR_PAY', 'waiting for pay'), ('SENT', 'sent'), ('CANCELED', 'canceled'), ('DELIVERED', 'delivered')], max_length=100),
        ),
    ]
