# Generated by Django 3.2.7 on 2021-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211008_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('MESHOP', 'meshop'), ('POST', 'post')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAY', 1), ('PROCESSING', 2), ('SENT', 3), ('DELIVERED', 4), ('CANCELED', 0)], default='WAITING_FOR_PAY', max_length=100, verbose_name='وضعیت سفارش'),
        ),
    ]
