# Generated by Django 3.2.7 on 2021-10-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211008_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('saved', 'saved')], default='فعال', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('MESHOP', 'meshop'), ('POST', 'post')], max_length=50, verbose_name='نوع ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_PAY', 1), ('PROCESSING', 2), ('SENT', 3), ('DELIVERED', 4), ('CANCELED', 0)], default=1, max_length=100, verbose_name='وضعیت سفارش'),
        ),
    ]
