# Generated by Django 3.2.7 on 2021-09-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_state'),
        ('order', '0004_auto_20210929_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='number',
            field=models.PositiveIntegerField(default=None, verbose_name='تعداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتری'),
        ),
    ]
