# Generated by Django 3.2.7 on 2021-10-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_receiver_phone'),
        ('order', '0004_auto_20211012_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='customer.address', verbose_name='آدرس'),
            preserve_default=False,
        ),
    ]
