# Generated by Django 3.2.7 on 2021-10-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIAL', 0), ('WAITING_FOR_PAY', 1), ('PROCESSING', 2), ('SENT', 3), ('DELIVERED', 4), ('CANCELED', -1)], default=1, max_length=100, verbose_name='وضعیت سفارش'),
        ),
    ]
