# Generated by Django 3.2.7 on 2021-09-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcolor_color'),
        ('order', '0005_auto_20210929_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor', verbose_name='رنگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.propertydescription', verbose_name='ویژگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
    ]
