# Generated by Django 3.2.7 on 2021-10-13 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.cart', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIAL', 0), ('WAITING_FOR_PAY', 1), ('PROCESSING', 2), ('SENT', 3), ('DELIVERED', 4), ('CANCELED', -1)], default=0, max_length=100, verbose_name='وضعیت سفارش'),
        ),
    ]
