# Generated by Django 3.2.7 on 2021-09-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcolor_color'),
        ('order', '0006_auto_20210929_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productfactorproperty', verbose_name='ویژگی'),
        ),
    ]
