# Generated by Django 3.2.7 on 2021-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210929_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('saved', 'saved')], default='فعال', max_length=10, verbose_name='وضعیت'),
        ),
    ]
