# Generated by Django 3.2.7 on 2021-10-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 1), ('CASH_ON_DELIVERY', 2), ('MECOIN', 3)], default=1, max_length=100, verbose_name='نحوه ی پرداخت'),
        ),
    ]
