# Generated by Django 3.2.7 on 2021-10-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
