# Generated by Django 3.2.7 on 2021-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[(1, 'ONLINE'), (2, 'CASH_ON_DELIVERY'), (3, 'MECOIN')], default=1, max_length=100, verbose_name='نحوه ی پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'INITIAL'), (1, 'WAITING_FOR_PAY'), (2, 'PROCESSING'), (3, 'SENT'), (4, 'DELIVERED'), (-1, 'CANCELED')], default=0, max_length=100, verbose_name='وضعیت سفارش'),
        ),
    ]
