# Generated by Django 3.2.7 on 2021-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211013_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('CASH_ON_DELIVERY', 'CASH_ON_DELIVERY'), ('MECOIN', 'MECOIN')], default='ONLINE', max_length=100, verbose_name='نحوه ی پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'INITIAL'), ('WAITING_FOR_PAY', 'WAITING_FOR_PAY'), ('PROCESSING', 'PROCESSING'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('CANCELED', 'CANCELED')], default='INITIAL', max_length=100, verbose_name='وضعیت سفارش'),
        ),
    ]
